package:
  name: libqglviewer
  version: 2.6.4

source:
  git_url: https://github.com/GillesDebunne/libQGLViewer
  git_tag: v2.6.4
  patches:
   # List any patch files here
   - QGLViewer_pro.patch
   - examples.pri.patch
   - libQGLViewer.pro.patch

build:
  number: 1
  features:
    - vc14 [win]

requirements:
  build:
    - qt
    - patch
  run:
    # python dependency is here due to libboost-python library that depends on
    # python version
    - qt

about:
  home: http://www.libqglviewer.com
  license: GPL
